'use client';

import Link from 'next/link';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-white">
      <Navigation />

      <main className="pt-24 pb-16 px-4 sm:px-6">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 tracking-tight mb-2">
            Terms of Service
          </h1>
          <p className="text-slate-500 mb-8">Last updated: January 8, 2025</p>

          <div className="prose prose-slate max-w-none">
            <section className="mb-8">
              <h2 className="text-xl font-bold text-slate-900 mb-4">1. Acceptance of Terms</h2>
              <p className="text-slate-600 mb-4">
                By accessing or using VentureCounsel.AI (the &quot;Service&quot;), operated by Shapiro Venture Law PLLC (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, you may not access or use the Service.
              </p>
              <p className="text-slate-600">
                We reserve the right to modify these Terms at any time. Your continued use of the Service after any such changes constitutes your acceptance of the new Terms.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-bold text-slate-900 mb-4">2. Description of Service</h2>
              <p className="text-slate-600 mb-4">
                VentureCounsel.AI provides AI-powered analytical tools designed to assist users in evaluating term sheets, compensation packages, and related startup documentation. The Service includes, but is not limited to:
              </p>
              <ul className="list-disc pl-6 text-slate-600 mb-4 space-y-2">
                <li>Term Sheet Reality Checker</li>
                <li>Compensation Mix Optimizer</li>
                <li>AI-powered chat functionality</li>
                <li>Document analysis and benchmarking tools</li>
              </ul>
            </section>

            <section className="mb-8 bg-amber-50 border border-amber-200 rounded-lg p-6">
              <h2 className="text-xl font-bold text-amber-900 mb-4">3. NO LEGAL ADVICE DISCLAIMER</h2>
              <p className="text-amber-800 mb-4 font-semibold">
                THIS IS THE MOST IMPORTANT SECTION OF THESE TERMS. PLEASE READ IT CAREFULLY.
              </p>
              <p className="text-slate-700 mb-4">
                <strong>VentureCounsel.AI is an AI-powered informational tool and does NOT provide legal advice.</strong> The Service is designed to provide general information and educational content to help users better understand term sheets, compensation structures, and related startup matters.
              </p>
              <p className="text-slate-700 mb-4">
                <strong>The information provided by the Service:</strong>
              </p>
              <ul className="list-disc pl-6 text-slate-700 mb-4 space-y-2">
                <li>Is NOT a substitute for advice from a qualified attorney</li>
                <li>Should NOT be relied upon as legal advice</li>
                <li>Does NOT create an attorney-client relationship between you and Shapiro Venture Law PLLC or any attorney</li>
                <li>May NOT reflect the most current legal developments</li>
                <li>May NOT be applicable to your specific circumstances</li>
                <li>Is generated by artificial intelligence and may contain errors or inaccuracies</li>
              </ul>
              <p className="text-slate-700 mb-4">
                <strong>You acknowledge and agree that:</strong>
              </p>
              <ul className="list-disc pl-6 text-slate-700 mb-4 space-y-2">
                <li>No attorney-client relationship is formed by your use of this Service</li>
                <li>No attorney-client privilege attaches to any information you submit to the Service</li>
                <li>Shapiro Venture Law PLLC is not your attorney by virtue of your use of this Service</li>
                <li>You will consult with a qualified attorney before making any legal decisions</li>
                <li>You will not rely solely on the output of this Service for any legal, financial, or business decisions</li>
              </ul>
              <p className="text-slate-700 font-semibold">
                FOR CRITICAL TRANSACTIONS, LEGAL MATTERS, OR ANY SITUATION WITH SIGNIFICANT CONSEQUENCES, ALWAYS CONSULT A QUALIFIED ATTORNEY LICENSED IN YOUR JURISDICTION.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-bold text-slate-900 mb-4">4. No Attorney-Client Relationship</h2>
              <p className="text-slate-600 mb-4">
                Your use of VentureCounsel.AI does not create an attorney-client relationship between you and Shapiro Venture Law PLLC, or between you and any attorney associated with Shapiro Venture Law PLLC. Communications through the Service are not privileged or confidential in the way attorney-client communications would be.
              </p>
              <p className="text-slate-600 mb-4">
                If you desire to engage Shapiro Venture Law PLLC for legal representation, you must do so through a separate, written engagement agreement. Use of this Service does not constitute or imply such an engagement.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-bold text-slate-900 mb-4">5. User Responsibilities</h2>
              <p className="text-slate-600 mb-4">
                You agree to:
              </p>
              <ul className="list-disc pl-6 text-slate-600 mb-4 space-y-2">
                <li>Use the Service only for lawful purposes</li>
                <li>Not upload or submit any content that is illegal, harmful, threatening, abusive, or otherwise objectionable</li>
                <li>Not attempt to gain unauthorized access to any portion of the Service</li>
                <li>Not use the Service to infringe upon the intellectual property rights of others</li>
                <li>Not reverse engineer, decompile, or disassemble any aspect of the Service</li>
                <li>Ensure you have proper authorization before uploading any confidential or proprietary documents</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-bold text-slate-900 mb-4">6. Confidentiality Warning</h2>
              <p className="text-slate-600 mb-4">
                <strong>Important:</strong> Information you submit to the Service may be processed by third-party AI services. Before uploading any documents or entering any information:
              </p>
              <ul className="list-disc pl-6 text-slate-600 mb-4 space-y-2">
                <li>Ensure you have authorization to share such information</li>
                <li>Consider whether the information is subject to confidentiality obligations</li>
                <li>Understand that we cannot guarantee the confidentiality of information submitted to the Service</li>
                <li>Be aware that submitted information may be retained or processed by our AI service providers</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-bold text-slate-900 mb-4">7. Intellectual Property</h2>
              <p className="text-slate-600 mb-4">
                The Service, including its original content, features, and functionality, is owned by Shapiro Venture Law PLLC and is protected by copyright, trademark, and other intellectual property laws. You may not reproduce, distribute, modify, or create derivative works of any portion of the Service without our express written permission.
              </p>
              <p className="text-slate-600">
                You retain ownership of any content you submit to the Service. By submitting content, you grant us a limited, non-exclusive license to process such content solely for the purpose of providing the Service to you.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-bold text-slate-900 mb-4">8. Disclaimer of Warranties</h2>
              <p className="text-slate-600 mb-4">
                THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO:
              </p>
              <ul className="list-disc pl-6 text-slate-600 mb-4 space-y-2">
                <li>IMPLIED WARRANTIES OF MERCHANTABILITY</li>
                <li>FITNESS FOR A PARTICULAR PURPOSE</li>
                <li>NON-INFRINGEMENT</li>
                <li>ACCURACY, COMPLETENESS, OR RELIABILITY OF CONTENT</li>
                <li>UNINTERRUPTED OR ERROR-FREE OPERATION</li>
              </ul>
              <p className="text-slate-600">
                We do not warrant that the Service will meet your requirements, that results obtained from the Service will be accurate or reliable, or that any errors in the Service will be corrected.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-bold text-slate-900 mb-4">9. Limitation of Liability</h2>
              <p className="text-slate-600 mb-4">
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL SHAPIRO VENTURE LAW PLLC, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO:
              </p>
              <ul className="list-disc pl-6 text-slate-600 mb-4 space-y-2">
                <li>LOSS OF PROFITS, DATA, USE, OR GOODWILL</li>
                <li>BUSINESS INTERRUPTION</li>
                <li>COST OF PROCUREMENT OF SUBSTITUTE SERVICES</li>
                <li>ANY DAMAGES ARISING FROM YOUR USE OF OR INABILITY TO USE THE SERVICE</li>
                <li>ANY DAMAGES ARISING FROM RELIANCE ON ANY INFORMATION PROVIDED BY THE SERVICE</li>
              </ul>
              <p className="text-slate-600">
                OUR TOTAL LIABILITY FOR ANY CLAIMS ARISING FROM YOUR USE OF THE SERVICE SHALL NOT EXCEED THE AMOUNT YOU PAID US, IF ANY, FOR ACCESS TO THE SERVICE DURING THE TWELVE (12) MONTHS PRECEDING THE CLAIM.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-bold text-slate-900 mb-4">10. Indemnification</h2>
              <p className="text-slate-600">
                You agree to indemnify, defend, and hold harmless Shapiro Venture Law PLLC and its officers, directors, employees, agents, and affiliates from and against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys&apos; fees) arising from or relating to your use of the Service, your violation of these Terms, or your violation of any rights of a third party.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-bold text-slate-900 mb-4">11. AI-Generated Content</h2>
              <p className="text-slate-600 mb-4">
                You acknowledge that the Service uses artificial intelligence to generate content and analysis. AI-generated content:
              </p>
              <ul className="list-disc pl-6 text-slate-600 mb-4 space-y-2">
                <li>May contain errors, inaccuracies, or outdated information</li>
                <li>Should be independently verified before reliance</li>
                <li>May not reflect the views or opinions of Shapiro Venture Law PLLC</li>
                <li>Is not a substitute for professional legal, financial, or business advice</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-bold text-slate-900 mb-4">12. Termination</h2>
              <p className="text-slate-600">
                We reserve the right to terminate or suspend your access to the Service at any time, without notice, for any reason, including if we reasonably believe you have violated these Terms. Upon termination, your right to use the Service will immediately cease.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-bold text-slate-900 mb-4">13. Governing Law</h2>
              <p className="text-slate-600">
                These Terms shall be governed by and construed in accordance with the laws of the State of Texas, without regard to its conflict of law provisions. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the state and federal courts located in Texas.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-bold text-slate-900 mb-4">14. Severability</h2>
              <p className="text-slate-600">
                If any provision of these Terms is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary so that these Terms shall otherwise remain in full force and effect.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-bold text-slate-900 mb-4">15. Entire Agreement</h2>
              <p className="text-slate-600">
                These Terms, together with our Privacy Policy, constitute the entire agreement between you and Shapiro Venture Law PLLC regarding your use of the Service and supersede all prior agreements and understandings.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-bold text-slate-900 mb-4">16. Contact Information</h2>
              <p className="text-slate-600 mb-4">
                If you have any questions about these Terms, please contact us at:
              </p>
              <p className="text-slate-600">
                <strong>Shapiro Venture Law PLLC</strong><br />
                Email: info@venturecounsel.ai
              </p>
            </section>
          </div>

          <div className="mt-12 pt-8 border-t border-slate-200">
            <Link href="/" className="text-blue-600 hover:text-blue-800 font-medium">
              &larr; Back to Home
            </Link>
          </div>
        </div>
      </main>

      <Footer showDisclaimer={false} />
    </div>
  );
}
